server:
  port: 8080
  servlet:
    contextPath: /barbershop

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default_schema: barbershop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bs
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: barbershop

