server:
  port: 8080
  servlet:
    contextPath: /barbershop

spring:
  jpa:
    database: POSTGRESQL
    #show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        default_schema: barbershop
        #format:sql: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bs
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: barbershop

logging:
  level:
    jdbc:
      connection: off
      audit: off
      timing: off
      resultset: off
      resultsettable: off
      sqltiming: off
      sqlonly: info